version: "3.7"
services:
  web:
    container_name: web
    build: website/.
    ports:
      - "8000"
    volumes:
      - "./website/app:/app"
  server:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
