apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: master
          image: web
          ports:
            - containerPort: 80
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - name: http
      port: 80
      targetPort: 80
      NodePort: 80
      protocol: TCP